# IMAGES
IMAGE_WIDTH = 154
IMAGE_HEIGHT = 145
IMAGE_MARGIN_LEFT = 81
IMAGE_MARGIN_BOTTOM = 351

# GLOBALS
SERVICE1_Y = 295
SERVICE_AND_PRICE_MARGIN = 150
MARGIN_BETWEEN_SERVICES = 15
TOTAL_PRICE_Y = 40
DISCOUNT_PRICE_Y = 73

# PLAN1
PLAN1_SERVICES_X = 65
PLAN1_TOTAL_PRICE_X = 180
PLAN1_DISCOUNT_PRICE_X = PLAN1_TOTAL_PRICE_X - 45

# PLAN2
PLAN2_SERVICES_X = 310
PLAN2_TOTAL_PRICE_X = 420
PLAN2_DISCOUNT_PRICE_X = PLAN2_TOTAL_PRICE_X - 45

# PLAN3
PLAN3_SERVICES_X = 545
PLAN3_TOTAL_PRICE_X = 660
PLAN3_DISCOUNT_PRICE_X = PLAN3_TOTAL_PRICE_X - 45

# COLORS
PLAN1_COLOR = PLAN3_COLOR = '#0A1C41'
PLAN2_COLOR = '#F2F2F2'
PLAN2_TOTAL_PRICE_COLOR = '#0A1C41'
PLAN1_TOTAL_PRICE_COLOR = PLAN3_TOTAL_PRICE_COLOR = '#F2F2F2'


# SUBTOTALs
SUBTOTAL_PRICE_Y = 90
PLAN1_SUBTOTAL_PRICE_X = PLAN1_TOTAL_PRICE_X - 15
PLAN2_SUBTOTAL_PRICE_X = PLAN2_TOTAL_PRICE_X - 15
PLAN3_SUBTOTAL_PRICE_X = PLAN3_TOTAL_PRICE_X - 15


# OTHERS
EXCEL_FILE_NAME = 'Eclipse Procedure Prices.xlsx'